# Generated by Django 5.1.3 on 2024-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='reference_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
