# Generated by Django 5.1.3 on 2024-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
