# Generated by Django 5.1.3 on 2024-12-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_customerreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
